import {v1 as uuid} from 'uuid';

export const CountryList = [
  {
    id:uuid(),
    name: 'Israel',
    dialCode: '+972',
    code: 'IL',
  },
  {
    id:uuid(),
    name: 'Afghanistan',
    dialCode: '+93',
    code: 'AF',
  },
  {
    id:uuid(),
    name: 'Albania',
    dialCode: '+355',
    code: 'AL',
  },
  {
    id:uuid(),
    name: 'Algeria',
    dialCode: '+213',
    code: 'DZ',
  },
  {
    id:uuid(),
    name: 'AmericanSamoa',
    dialCode: '+1 684',
    code: 'AS',
  },
  {
    id:uuid(),
    name: 'Andorra',
    dialCode: '+376',
    code: 'AD',
  },
  {
    id:uuid(),
    name: 'Angola',
    dialCode: '+244',
    code: 'AO',
  },
  {
    id:uuid(),
    name: 'Anguilla',
    dialCode: '+1 264',
    code: 'AI',
  },
  {
    id:uuid(),
    name: 'Antigua and Barbuda',
    dialCode: '+1268',
    code: 'AG',
  },
  {
    id:uuid(),
    name: 'Argentina',
    dialCode: '+54',
    code: 'AR',
  },
  {
    id:uuid(),
    name: 'Armenia',
    dialCode: '+374',
    code: 'AM',
  },
  {
    id:uuid(),
    name: 'Aruba',
    dialCode: '+297',
    code: 'AW',
  },
  {
    id:uuid(),
    name: 'Australia',
    dialCode: '+61',
    code: 'AU',
  },
  {
    id:uuid(),
    name: 'Austria',
    dialCode: '+43',
    code: 'AT',
  },
  {
    id:uuid(),
    name: 'Azerbaijan',
    dialCode: '+994',
    code: 'AZ',
  },
  {
    id:uuid(),
    name: 'Bahamas',
    dialCode: '+1 242',
    code: 'BS',
  },
  {
    id:uuid(),
    name: 'Bahrain',
    dialCode: '+973',
    code: 'BH',
  },
  {
    id:uuid(),
    name: 'Bangladesh',
    dialCode: '+880',
    code: 'BD',
  },
  {
    id:uuid(),
    name: 'Barbados',
    dialCode: '+1 246',
    code: 'BB',
  },
  {
    id:uuid(),
    name: 'Belarus',
    dialCode: '+375',
    code: 'BY',
  },
  {
    id:uuid(),
    name: 'Belgium',
    dialCode: '+32',
    code: 'BE',
  },
  {
    id:uuid(),
    name: 'Belize',
    dialCode: '+501',
    code: 'BZ',
  },
  {
    id:uuid(),
    name: 'Benin',
    dialCode: '+229',
    code: 'BJ',
  },
  {
    id:uuid(),
    name: 'Bermuda',
    dialCode: '+1 441',
    code: 'BM',
  },
  {
    id:uuid(),
    name: 'Bhutan',
    dialCode: '+975',
    code: 'BT',
  },
  {
    id:uuid(),
    name: 'Bosnia and Herzegovina',
    dialCode: '+387',
    code: 'BA',
  },
  {
    id:uuid(),
    name: 'Botswana',
    dialCode: '+267',
    code: 'BW',
  },
  {
    id:uuid(),
    name: 'Brazil',
    dialCode: '+55',
    code: 'BR',
  },
  {
    id:uuid(),
    name: 'British Indian Ocean Territory',
    dialCode: '+246',
    code: 'IO',
  },
  {
    id:uuid(),
    name: 'Bulgaria',
    dialCode: '+359',
    code: 'BG',
  },
  {
    id:uuid(),
    name: 'Burkina Faso',
    dialCode: '+226',
    code: 'BF',
  },
  {
    id:uuid(),
    name: 'Burundi',
    dialCode: '+257',
    code: 'BI',
  },
  {
    id:uuid(),
    name: 'Cambodia',
    dialCode: '+855',
    code: 'KH',
  },
  {
    id:uuid(),
    name: 'Cameroon',
    dialCode: '+237',
    code: 'CM',
  },
  {
    id:uuid(),
    name: 'Canada',
    dialCode: '+1',
    code: 'CA',
  },
  {
    id:uuid(),
    name: 'Cape Verde',
    dialCode: '+238',
    code: 'CV',
  },
  {
    id:uuid(),
    name: 'Cayman Islands',
    dialCode: '+ 345',
    code: 'KY',
  },
  {
    id:uuid(),
    name: 'Central African Republic',
    dialCode: '+236',
    code: 'CF',
  },
  {
    id:uuid(),
    name: 'Chad',
    dialCode: '+235',
    code: 'TD',
  },
  {
    id:uuid(),
    name: 'Chile',
    dialCode: '+56',
    code: 'CL',
  },
  {
    id:uuid(),
    name: 'China',
    dialCode: '+86',
    code: 'CN',
  },
  {
    id:uuid(),
    name: 'Christmas Island',
    dialCode: '+61',
    code: 'CX',
  },
  {
    id:uuid(),
    name: 'Colombia',
    dialCode: '+57',
    code: 'CO',
  },
  {
    id:uuid(),
    name: 'Comoros',
    dialCode: '+269',
    code: 'KM',
  },
  {
    id:uuid(),
    name: 'Congo',
    dialCode: '+242',
    code: 'CG',
  },
  {
    id:uuid(),
    name: 'Cook Islands',
    dialCode: '+682',
    code: 'CK',
  },
  {
    id:uuid(),
    name: 'Costa Rica',
    dialCode: '+506',
    code: 'CR',
  },
  {
    id:uuid(),
    name: 'Croatia',
    dialCode: '+385',
    code: 'HR',
  },
  {
    id:uuid(),
    name: 'Cuba',
    dialCode: '+53',
    code: 'CU',
  },
  {
    id:uuid(),
    name: 'Cyprus',
    dialCode: '+537',
    code: 'CY',
  },
  {
    id:uuid(),
    name: 'Czech Republic',
    dialCode: '+420',
    code: 'CZ',
  },
  {
    id:uuid(),
    name: 'Denmark',
    dialCode: '+45',
    code: 'DK',
  },
  {
    id:uuid(),
    name: 'Djibouti',
    dialCode: '+253',
    code: 'DJ',
  },
  {
    id:uuid(),
    name: 'Dominica',
    dialCode: '+1 767',
    code: 'DM',
  },
  {
    id:uuid(),
    name: 'Dominican Republic',
    dialCode: '+1 849',
    code: 'DO',
  },
  {
    id:uuid(),
    name: 'Ecuador',
    dialCode: '+593',
    code: 'EC',
  },
  {
    id:uuid(),
    name: 'Egypt',
    dialCode: '+20',
    code: 'EG',
  },
  {
    id:uuid(),
    name: 'El Salvador',
    dialCode: '+503',
    code: 'SV',
  },
  {
    id:uuid(),
    name: 'Equatorial Guinea',
    dialCode: '+240',
    code: 'GQ',
  },
  {
    id:uuid(),
    name: 'Eritrea',
    dialCode: '+291',
    code: 'ER',
  },
  {
    id:uuid(),
    name: 'Estonia',
    dialCode: '+372',
    code: 'EE',
  },
  {
    id:uuid(),
    name: 'Ethiopia',
    dialCode: '+251',
    code: 'ET',
  },
  {
    id:uuid(),
    name: 'Faroe Islands',
    dialCode: '+298',
    code: 'FO',
  },
  {
    id:uuid(),
    name: 'Fiji',
    dialCode: '+679',
    code: 'FJ',
  },
  {
    id:uuid(),
    name: 'Finland',
    dialCode: '+358',
    code: 'FI',
  },
  {
    id:uuid(),
    name: 'France',
    dialCode: '+33',
    code: 'FR',
  },
  {
    id:uuid(),
    name: 'French Guiana',
    dialCode: '+594',
    code: 'GF',
  },
  {
    id:uuid(),
    name: 'French Polynesia',
    dialCode: '+689',
    code: 'PF',
  },
  {
    id:uuid(),
    name: 'Gabon',
    dialCode: '+241',
    code: 'GA',
  },
  {
    id:uuid(),
    name: 'Gambia',
    dialCode: '+220',
    code: 'GM',
  },
  {
    id:uuid(),
    name: 'Georgia',
    dialCode: '+995',
    code: 'GE',
  },
  {
    id:uuid(),
    name: 'Germany',
    dialCode: '+49',
    code: 'DE',
  },
  {
    id:uuid(),
    name: 'Ghana',
    dialCode: '+233',
    code: 'GH',
  },
  {
    id:uuid(),
    name: 'Gibraltar',
    dialCode: '+350',
    code: 'GI',
  },
  {
    id:uuid(),
    name: 'Greece',
    dialCode: '+30',
    code: 'GR',
  },
  {
    id:uuid(),
    name: 'Greenland',
    dialCode: '+299',
    code: 'GL',
  },
  {
    id:uuid(),
    name: 'Grenada',
    dialCode: '+1 473',
    code: 'GD',
  },
  {
    id:uuid(),
    name: 'Guadeloupe',
    dialCode: '+590',
    code: 'GP',
  },
  {
    id:uuid(),
    name: 'Guam',
    dialCode: '+1 671',
    code: 'GU',
  },
  {
    id:uuid(),
    name: 'Guatemala',
    dialCode: '+502',
    code: 'GT',
  },
  {
    id:uuid(),
    name: 'Guinea',
    dialCode: '+224',
    code: 'GN',
  },
  {
    id:uuid(),
    name: 'Guinea-Bissau',
    dialCode: '+245',
    code: 'GW',
  },
  {
    id:uuid(),
    name: 'Guyana',
    dialCode: '+595',
    code: 'GY',
  },
  {
    id:uuid(),
    name: 'Haiti',
    dialCode: '+509',
    code: 'HT',
  },
  {
    id:uuid(),
    name: 'Honduras',
    dialCode: '+504',
    code: 'HN',
  },
  {
    id:uuid(),
    name: 'Hungary',
    dialCode: '+36',
    code: 'HU',
  },
  {
    id:uuid(),
    name: 'Iceland',
    dialCode: '+354',
    code: 'IS',
  },
  {
    id:uuid(),
    name: 'India',
    dialCode: '+91',
    code: 'IN',
  },
  {
    id:uuid(),
    name: 'Indonesia',
    dialCode: '+62',
    code: 'ID',
  },
  {
    id:uuid(),
    name: 'Iraq',
    dialCode: '+964',
    code: 'IQ',
  },
  {
    id:uuid(),
    name: 'Ireland',
    dialCode: '+353',
    code: 'IE',
  },
  {
    id:uuid(),
    name: 'Israel',
    dialCode: '+972',
    code: 'IL',
  },
  {
    id:uuid(),
    name: 'Italy',
    dialCode: '+39',
    code: 'IT',
  },
  {
    id:uuid(),
    name: 'Jamaica',
    dialCode: '+1 876',
    code: 'JM',
  },
  {
    id:uuid(),
    name: 'Japan',
    dialCode: '+81',
    code: 'JP',
  },
  {
    id:uuid(),
    name: 'Jordan',
    dialCode: '+962',
    code: 'JO',
  },
  {
    id:uuid(),
    name: 'Kazakhstan',
    dialCode: '+7 7',
    code: 'KZ',
  },
  {
    id:uuid(),
    name: 'Kenya',
    dialCode: '+254',
    code: 'KE',
  },
  {
    id:uuid(),
    name: 'Kiribati',
    dialCode: '+686',
    code: 'KI',
  },
  {
    id:uuid(),
    name: 'Kuwait',
    dialCode: '+965',
    code: 'KW',
  },
  {
    id:uuid(),
    name: 'Kyrgyzstan',
    dialCode: '+996',
    code: 'KG',
  },
  {
    id:uuid(),
    name: 'Latvia',
    dialCode: '+371',
    code: 'LV',
  },
  {
    id:uuid(),
    name: 'Lebanon',
    dialCode: '+961',
    code: 'LB',
  },
  {
    id:uuid(),
    name: 'Lesotho',
    dialCode: '+266',
    code: 'LS',
  },
  {
    id:uuid(),
    name: 'Liberia',
    dialCode: '+231',
    code: 'LR',
  },
  {
    id:uuid(),
    name: 'Liechtenstein',
    dialCode: '+423',
    code: 'LI',
  },
  {
    id:uuid(),
    name: 'Lithuania',
    dialCode: '+370',
    code: 'LT',
  },
  {
    id:uuid(),
    name: 'Luxembourg',
    dialCode: '+352',
    code: 'LU',
  },
  {
    id:uuid(),
    name: 'Madagascar',
    dialCode: '+261',
    code: 'MG',
  },
  {
    id:uuid(),
    name: 'Malawi',
    dialCode: '+265',
    code: 'MW',
  },
  {
    id:uuid(),
    name: 'Malaysia',
    dialCode: '+60',
    code: 'MY',
  },
  {
    id:uuid(),
    name: 'Maldives',
    dialCode: '+960',
    code: 'MV',
  },
  {
    id:uuid(),
    name: 'Mali',
    dialCode: '+223',
    code: 'ML',
  },
  {
    id:uuid(),
    name: 'Malta',
    dialCode: '+356',
    code: 'MT',
  },
  {
    id:uuid(),
    name: 'Marshall Islands',
    dialCode: '+692',
    code: 'MH',
  },
  {
    id:uuid(),
    name: 'Martinique',
    dialCode: '+596',
    code: 'MQ',
  },
  {
    id:uuid(),
    name: 'Mauritania',
    dialCode: '+222',
    code: 'MR',
  },
  {
    id:uuid(),
    name: 'Mauritius',
    dialCode: '+230',
    code: 'MU',
  },
  {
    id:uuid(),
    name: 'Mayotte',
    dialCode: '+262',
    code: 'YT',
  },
  {
    id:uuid(),
    name: 'Mexico',
    dialCode: '+52',
    code: 'MX',
  },
  {
    id:uuid(),
    name: 'Monaco',
    dialCode: '+377',
    code: 'MC',
  },
  {
    id:uuid(),
    name: 'Mongolia',
    dialCode: '+976',
    code: 'MN',
  },
  {
    id:uuid(),
    name: 'Montenegro',
    dialCode: '+382',
    code: 'ME',
  },
  {
    id:uuid(),
    name: 'Montserrat',
    dialCode: '+1664',
    code: 'MS',
  },
  {
    id:uuid(),
    name: 'Morocco',
    dialCode: '+212',
    code: 'MA',
  },
  {
    id:uuid(),
    name: 'Myanmar',
    dialCode: '+95',
    code: 'MM',
  },
  {
    id:uuid(),
    name: 'Namibia',
    dialCode: '+264',
    code: 'NA',
  },
  {
    id:uuid(),
    name: 'Nauru',
    dialCode: '+674',
    code: 'NR',
  },
  {
    id:uuid(),
    name: 'Nepal',
    dialCode: '+977',
    code: 'NP',
  },
  {
    id:uuid(),
    name: 'Netherlands',
    dialCode: '+31',
    code: 'NL',
  },
  {
    id:uuid(),
    name: 'Netherlands Antilles',
    dialCode: '+599',
    code: 'AN',
  },
  {
    id:uuid(),
    name: 'New Caledonia',
    dialCode: '+687',
    code: 'NC',
  },
  {
    id:uuid(),
    name: 'New Zealand',
    dialCode: '+64',
    code: 'NZ',
  },
  {
    id:uuid(),
    name: 'Nicaragua',
    dialCode: '+505',
    code: 'NI',
  },
  {
    id:uuid(),
    name: 'Niger',
    dialCode: '+227',
    code: 'NE',
  },
  {
    id:uuid(),
    name: 'Nigeria',
    dialCode: '+234',
    code: 'NG',
  },
  {
    id:uuid(),
    name: 'Niue',
    dialCode: '+683',
    code: 'NU',
  },
  {
    id:uuid(),
    name: 'Norfolk Island',
    dialCode: '+672',
    code: 'NF',
  },
  {
    id:uuid(),
    name: 'Northern Mariana Islands',
    dialCode: '+1 670',
    code: 'MP',
  },
  {
    id:uuid(),
    name: 'Norway',
    dialCode: '+47',
    code: 'NO',
  },
  {
    id:uuid(),
    name: 'Oman',
    dialCode: '+968',
    code: 'OM',
  },
  {
    id:uuid(),
    name: 'Pakistan',
    dialCode: '+92',
    code: 'PK',
  },
  {
    id:uuid(),
    name: 'Palau',
    dialCode: '+680',
    code: 'PW',
  },
  {
    id:uuid(),
    name: 'Panama',
    dialCode: '+507',
    code: 'PA',
  },
  {
    id:uuid(),
    name: 'Papua New Guinea',
    dialCode: '+675',
    code: 'PG',
  },
  {
    id:uuid(),
    name: 'Paraguay',
    dialCode: '+595',
    code: 'PY',
  },
  {
    id:uuid(),
    name: 'Peru',
    dialCode: '+51',
    code: 'PE',
  },
  {
    id:uuid(),
    name: 'Philippines',
    dialCode: '+63',
    code: 'PH',
  },
  {
    id:uuid(),
    name: 'Poland',
    dialCode: '+48',
    code: 'PL',
  },
  {
    id:uuid(),
    name: 'Portugal',
    dialCode: '+351',
    code: 'PT',
  },
  {
    id:uuid(),
    name: 'Puerto Rico',
    dialCode: '+1 939',
    code: 'PR',
  },
  {
    id:uuid(),
    name: 'Qatar',
    dialCode: '+974',
    code: 'QA',
  },
  {
    id:uuid(),
    name: 'Romania',
    dialCode: '+40',
    code: 'RO',
  },
  {
    id:uuid(),
    name: 'Rwanda',
    dialCode: '+250',
    code: 'RW',
  },
  {
    id:uuid(),
    name: 'Samoa',
    dialCode: '+685',
    code: 'WS',
  },
  {
    id:uuid(),
    name: 'San Marino',
    dialCode: '+378',
    code: 'SM',
  },
  {
    id:uuid(),
    name: 'Saudi Arabia',
    dialCode: '+966',
    code: 'SA',
  },
  {
    id:uuid(),
    name: 'Senegal',
    dialCode: '+221',
    code: 'SN',
  },
  {
    id:uuid(),
    name: 'Serbia',
    dialCode: '+381',
    code: 'RS',
  },
  {
    id:uuid(),
    name: 'Seychelles',
    dialCode: '+248',
    code: 'SC',
  },
  {
    id:uuid(),
    name: 'Sierra Leone',
    dialCode: '+232',
    code: 'SL',
  },
  {
    id:uuid(),
    name: 'Singapore',
    dialCode: '+65',
    code: 'SG',
  },
  {
    id:uuid(),
    name: 'Slovakia',
    dialCode: '+421',
    code: 'SK',
  },
  {
    id:uuid(),
    name: 'Slovenia',
    dialCode: '+386',
    code: 'SI',
  },
  {
    id:uuid(),
    name: 'Solomon Islands',
    dialCode: '+677',
    code: 'SB',
  },
  {
    id:uuid(),
    name: 'South Africa',
    dialCode: '+27',
    code: 'ZA',
  },
  {
    id:uuid(),
    name: 'South Georgia and the South Sandwich Islands',
    dialCode: '+500',
    code: 'GS',
  },
  {
    id:uuid(),
    name: 'Spain',
    dialCode: '+34',
    code: 'ES',
  },
  {
    id:uuid(),
    name: 'Sri Lanka',
    dialCode: '+94',
    code: 'LK',
  },
  {
    id:uuid(),
    name: 'Sudan',
    dialCode: '+249',
    code: 'SD',
  },
  {
    id:uuid(),
    name: 'Suriname',
    dialCode: '+597',
    code: 'SR',
  },
  {
    id:uuid(),
    name: 'Swaziland',
    dialCode: '+268',
    code: 'SZ',
  },
  {
    id:uuid(),
    name: 'Sweden',
    dialCode: '+46',
    code: 'SE',
  },
  {
    id:uuid(),
    name: 'Switzerland',
    dialCode: '+41',
    code: 'CH',
  },
  {
    id:uuid(),
    name: 'Tajikistan',
    dialCode: '+992',
    code: 'TJ',
  },
  {
    id:uuid(),
    name: 'Thailand',
    dialCode: '+66',
    code: 'TH',
  },
  {
    id:uuid(),
    name: 'Togo',
    dialCode: '+228',
    code: 'TG',
  },
  {
    id:uuid(),
    name: 'Tokelau',
    dialCode: '+690',
    code: 'TK',
  },
  {
    id:uuid(),
    name: 'Tonga',
    dialCode: '+676',
    code: 'TO',
  },
  {
    id:uuid(),
    name: 'Trinidad and Tobago',
    dialCode: '+1 868',
    code: 'TT',
  },
  {
    id:uuid(),
    name: 'Tunisia',
    dialCode: '+216',
    code: 'TN',
  },
  {
    id:uuid(),
    name: 'Turkey',
    dialCode: '+90',
    code: 'TR',
  },
  {
    id:uuid(),
    name: 'Turkmenistan',
    dialCode: '+993',
    code: 'TM',
  },
  {
    id:uuid(),
    name: 'Turks and Caicos Islands',
    dialCode: '+1 649',
    code: 'TC',
  },
  {
    id:uuid(),
    name: 'Tuvalu',
    dialCode: '+688',
    code: 'TV',
  },
  {
    id:uuid(),
    name: 'Uganda',
    dialCode: '+256',
    code: 'UG',
  },
  {
    id:uuid(),
    name: 'Ukraine',
    dialCode: '+380',
    code: 'UA',
  },
  {
    id:uuid(),
    name: 'United Arab Emirates',
    dialCode: '+971',
    code: 'AE',
  },
  {
    id:uuid(),
    name: 'United Kingdom',
    dialCode: '+44',
    code: 'GB',
  },
  {
    id:uuid(),
    name: 'United States',
    dialCode: '+1',
    code: 'US',
  },
  {
    id:uuid(),
    name: 'Uruguay',
    dialCode: '+598',
    code: 'UY',
  },
  {
    id:uuid(),
    name: 'Uzbekistan',
    dialCode: '+998',
    code: 'UZ',
  },
  {
    id:uuid(),
    name: 'Vanuatu',
    dialCode: '+678',
    code: 'VU',
  },
  {
    id:uuid(),
    name: 'Wallis and Futuna',
    dialCode: '+681',
    code: 'WF',
  },
  {
    id:uuid(),
    name: 'Yemen',
    dialCode: '+967',
    code: 'YE',
  },
  {
    id:uuid(),
    name: 'Zambia',
    dialCode: '+260',
    code: 'ZM',
  },
  {
    id:uuid(),
    name: 'Zimbabwe',
    dialCode: '+263',
    code: 'ZW',
  },
  {
    id:uuid(),
    name: 'land Islands',
    dialCode: '',
    code: 'AX',
  },
  {
    id:uuid(),
    name: 'Antarctica',
    dialCode: null,
    code: 'AQ',
  },
  {
    id:uuid(),
    name: 'Bolivia, Plurinational State of',
    dialCode: '+591',
    code: 'BO',
  },
  {
    id:uuid(),
    name: 'Brunei Darussalam',
    dialCode: '+673',
    code: 'BN',
  },
  {
    id:uuid(),
    name: 'Cocos (Keeling) Islands',
    dialCode: '+61',
    code: 'CC',
  },
  {
    id:uuid(),
    name: 'Congo, The Democratic Republic of the',
    dialCode: '+243',
    code: 'CD',
  },
  {
    id:uuid(),
    name: "Cote d'Ivoire",
    dialCode: '+225',
    code: 'CI',
  },
  {
    id:uuid(),
    name: 'Falkland Islands (Malvinas)',
    dialCode: '+500',
    code: 'FK',
  },
  {
    id:uuid(),
    name: 'Guernsey',
    dialCode: '+44',
    code: 'GG',
  },
  {
    id:uuid(),
    name: 'Holy See (Vatican City State)',
    dialCode: '+379',
    code: 'VA',
  },
  {
    id:uuid(),
    name: 'Hong Kong',
    dialCode: '+852',
    code: 'HK',
  },
  {
    id:uuid(),
    name: 'Iran, Islamic Republic of',
    dialCode: '+98',
    code: 'IR',
  },
  {
    id:uuid(),
    name: 'Isle of Man',
    dialCode: '+44',
    code: 'IM',
  },
  {
    id:uuid(),
    name: 'Jersey',
    dialCode: '+44',
    code: 'JE',
  },
  {
    id:uuid(),
    name: "Korea, Democratic People's Republic of",
    dialCode: '+850',
    code: 'KP',
  },
  {
    id:uuid(),
    name: 'Korea, Republic of',
    dialCode: '+82',
    code: 'KR',
  },
  {
    id:uuid(),
    name: "Lao People's Democratic Republic",
    dialCode: '+856',
    code: 'LA',
  },
  {
    id:uuid(),
    name: 'Libyan Arab Jamahiriya',
    dialCode: '+218',
    code: 'LY',
  },
  {
    id:uuid(),
    name: 'Macao',
    dialCode: '+853',
    code: 'MO',
  },
  {
    id:uuid(),
    name: 'Macedonia, The Former Yugoslav Republic of',
    dialCode: '+389',
    code: 'MK',
  },
  {
    id:uuid(),
    name: 'Micronesia, Federated States of',
    dialCode: '+691',
    code: 'FM',
  },
  {
    id:uuid(),
    name: 'Moldova, Republic of',
    dialCode: '+373',
    code: 'MD',
  },
  {
    id:uuid(),
    name: 'Mozambique',
    dialCode: '+258',
    code: 'MZ',
  },
  {
    id:uuid(),
    name: 'Palestinian Territory, Occupied',
    dialCode: '+970',
    code: 'PS',
  },
  {
    id:uuid(),
    name: 'Pitcairn',
    dialCode: '+872',
    code: 'PN',
  },
  {
    id:uuid(),
    name: 'Réunion',
    dialCode: '+262',
    code: 'RE',
  },
  {
    id:uuid(),
    name: 'Russia',
    dialCode: '+7',
    code: 'RU',
  },
  {
    id:uuid(),
    name: 'Saint Barthélemy',
    dialCode: '+590',
    code: 'BL',
  },
  {
    id:uuid(),
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dialCode: '+290',
    code: 'SH',
  },
  {
    id:uuid(),
    name: 'Saint Kitts and Nevis',
    dialCode: '+1 869',
    code: 'KN',
  },
  {
    id:uuid(),
    name: 'Saint Lucia',
    dialCode: '+1 758',
    code: 'LC',
  },
  {
    id:uuid(),
    name: 'Saint Martin',
    dialCode: '+590',
    code: 'MF',
  },
  {
    id:uuid(),
    name: 'Saint Pierre and Miquelon',
    dialCode: '+508',
    code: 'PM',
  },
  {
    id:uuid(),
    name: 'Saint Vincent and the Grenadines',
    dialCode: '+1 784',
    code: 'VC',
  },
  {
    id:uuid(),
    name: 'Sao Tome and Principe',
    dialCode: '+239',
    code: 'ST',
  },
  {
    id:uuid(),
    name: 'Somalia',
    dialCode: '+252',
    code: 'SO',
  },
  {
    id:uuid(),
    name: 'Svalbard and Jan Mayen',
    dialCode: '+47',
    code: 'SJ',
  },
  {
    id:uuid(),
    name: 'Syrian Arab Republic',
    dialCode: '+963',
    code: 'SY',
  },
  {
    id:uuid(),
    name: 'Taiwan, Province of China',
    dialCode: '+886',
    code: 'TW',
  },
  {
    id:uuid(),
    name: 'Tanzania, United Republic of',
    dialCode: '+255',
    code: 'TZ',
  },
  {
    id:uuid(),
    name: 'Timor-Leste',
    dialCode: '+670',
    code: 'TL',
  },
  {
    id:uuid(),
    name: 'Venezuela, Bolivarian Republic of',
    dialCode: '+58',
    code: 'VE',
  },
  {
    id:uuid(),
    name: 'Viet Nam',
    dialCode: '+84',
    code: 'VN',
  },
  {
    id:uuid(),
    name: 'Virgin Islands, British',
    dialCode: '+1 284',
    code: 'VG',
  },
  {
    id:uuid(),
    name: 'Virgin Islands, U.S.',
    dialCode: '+1 340',
    code: 'VI',
  },
];
